window.DIVARIS_INTERVENTIONS = {
  lifting: ['Lifting cervico-facial','Visage','Traite le relâchement du visage et du cou afin de restaurer l’ovale sans modifier l’identité.','L’examen analyse peau, muscles, graisse, bajoues, cou et asymétrie. Le geste peut associer dégraissage, remise en tension profonde, repositionnement des pommettes et redrapage cutané. Le site officiel indique une anesthésie générale et une durée habituelle de 1 h 30 à 2 h.','Pansement initial, œdème, ecchymoses et sensibilité diminuée sont possibles. Les fils sont contrôlés la première semaine et les cicatrices évoluent plusieurs mois.','https://www.marc-divaris.com/lifting-du-visage-cervicofacial-paris'],
  temporal: ['Lifting temporal et frontal','Visage','Remonte la partie externe du sourcil pour ouvrir le regard et corriger un relâchement temporal.','Une courte incision est cachée dans les cheveux. Les tissus profonds sont mobilisés jusqu’au sourcil puis fixés plus haut. Le lifting frontal répond à d’autres indications et est devenu moins fréquent depuis la toxine botulique.','Œdème et ecchymoses sont transitoires. La stabilisation des tissus et l’appréciation du résultat demandent plusieurs semaines.','https://www.marc-divaris.com/lifting-temporal-et-frontal'],
  pommettes: ['Lifting des pommettes','Visage','Restaure la position des tissus du milieu du visage et la transition entre la paupière et la joue.','Le geste agit en profondeur selon un vecteur vertical adapté au squelette. Il peut être associé à un lifting cervico-facial, une blépharoplastie ou un apport de volume.','Le gonflement initial masque le résultat, qui se précise lorsque les tissus retrouvent leur souplesse.','https://www.marc-divaris.com/lifting-des-pommettes'],
  cou: ['Lifting du cou','Visage','Redéfinit l’angle entre le menton et le cou et traite peau relâchée, graisse et bandes musculaires.','Selon l’anatomie, il associe liposuccion sous-mentonnière, remise en tension du muscle platysma et retrait cutané mesuré. Il accompagne souvent un lifting du visage.','Contention, gonflement, ecchymoses et sensibilité temporairement modifiée sont possibles.','https://www.marc-divaris.com/lifting-du-cou'],
  minilift: ['Mini-lift ou Soft lift','Visage','Correction plus limitée d’un relâchement débutant de l’ovale et des joues.','Les incisions et le décollement sont réduits, tout en travaillant la direction naturelle des tissus. Il ne remplace pas un lifting complet lorsque le cou ou la peau sont très relâchés.','La récupération est souvent plus courte, mais œdème, ecchymoses et soins de cicatrice restent attendus.','https://www.marc-divaris.com/mini-lift-soft-lift'],
  peeling: ['Peeling au phénol tamponné','Visage','Renouvellement cutané contrôlé destiné à certaines rides, taches et irrégularités profondes.','La profondeur et les zones sont choisies selon la peau et sa pigmentation. Le phénol est un acte médical profond, différent d’un peeling cosmétique superficiel.','Rougeur, desquamation et éviction sociale peuvent être importantes. Suivi et protection solaire stricte sont indispensables.','https://www.marc-divaris.com/peeling'],
  'lipo-visage': ['Liposuccion du visage','Visage','Retire des amas graisseux localisés pour mieux définir l’ovale, les bajoues ou le dessous du menton.','De fines canules passent par de petites incisions. La qualité de peau est déterminante ; un relâchement important peut conduire à proposer un lifting associé.','Gonflement et ecchymoses sont possibles. Une contention peut être prescrite et le résultat se précise progressivement.','https://www.marc-divaris.com/liposuccion-du-visage'],
  bichectomie: ['Bichectomie','Visage','Réduit les boules de Bichat afin d’affiner certaines joues durablement rondes.','Une courte incision est réalisée dans la bouche, sans cicatrice cutanée. L’indication doit rester prudente car le visage perd naturellement du volume avec l’âge.','Le gonflement est habituel. Hygiène buccale et consignes alimentaires accompagnent la cicatrisation.','https://www.marc-divaris.com/bichectomie'],
  rhino: ['Rhinoplastie','Visage','Remodèle le nez en recherchant un équilibre avec le profil et l’ensemble du visage.','L’analyse porte sur les os, cartilages, pointe, cloison, peau et respiration. La voie ouverte ou fermée et les gestes sont individualisés ; une simulation aide au dialogue sans garantir le résultat.','Une attelle est souvent portée une semaine. Œdème et ecchymoses diminuent progressivement, mais la pointe peut évoluer plusieurs mois.','https://www.marc-divaris.com/rhinoplastie'],
  menton: ['Remodelage du menton','Visage','Corrige projection, hauteur ou asymétrie du menton pour équilibrer le profil et le bas du visage.','La correction peut utiliser une modification osseuse, une prothèse, une injection ou de la graisse. L’occlusion et la mandibule sont évaluées avant le choix.','Les suites dépendent du geste ; gonflement, gêne et modification temporaire de sensibilité sont possibles.','https://www.marc-divaris.com/remodeler-le-menton'],
  blepharoplastie: ['Blépharoplastie','Regard','Corrige excès de peau et poches graisseuses en préservant l’expression du regard.','Les incisions supérieures sont cachées dans le pli. Pour certaines poches inférieures, une voie interne évite une cicatrice cutanée. L’examen peut inclure un bilan ophtalmologique.','Œdème et ecchymoses durent plusieurs jours. Les fils sont souvent retirés la première semaine et le résultat mûrit plusieurs mois.','https://www.marc-divaris.com/blepharoplastie'],
  filling: ['Lipofilling du visage et des cernes','Regard','Transfère la graisse du patient vers les cernes, tempes, joues ou pommettes creusées.','La graisse est prélevée, préparée puis réinjectée par microcanules. Une partie se résorbe ; une seconde séance peut être nécessaire.','Œdème et irrégularités temporaires sont possibles. Le volume stabilisé peut ensuite varier avec le poids.','https://www.marc-divaris.com/filling'],
  lipo: ['Liposuccion','Silhouette','Remodèle les contours en retirant des amas graisseux localisés ; ce n’est pas un traitement de l’obésité.','Les zones sont dessinées debout puis aspirées avec de fines canules. Qualité cutanée, régularité et limites de volume conditionnent le projet.','Œdème, ecchymoses et contention sont habituels. Le résultat continue d’évoluer pendant plusieurs mois.','https://www.marc-divaris.com/la-liposuccion'],
  culotte: ['Liposuccion de la culotte de cheval','Silhouette','Traite la graisse de la face externe des cuisses, souvent avec les hanches ou les genoux.','L’aspiration est répartie pour préserver des transitions naturelles entre cuisses, hanches et fesses.','Une contention est portée après l’intervention. Le résultat apparaît avec la disparition progressive de l’œdème.','https://www.marc-divaris.com/liposuccion-culotte-de-cheval'],
  bras: ['Liposuccion des bras','Silhouette','Allège un excès graisseux de la face interne ou postérieure des bras.','Elle convient surtout si la peau peut se rétracter. En cas d’excès cutané important, une brachioplastie peut être plus adaptée.','Contention, gonflement et limitation temporaire des efforts avec les bras sont fréquents.','https://www.marc-divaris.com/liposuccion-du-bras'],
  ventre: ['Liposuccion du ventre','Silhouette','Traite les amas sous-cutanés du ventre et de la taille lorsque peau et paroi restent suffisamment toniques.','L’examen distingue graisse aspirabile, graisse viscérale, relâchement cutané et écartement musculaire. Les flancs peuvent être associés.','Une gaine est généralement prescrite. Une abdominoplastie est indiquée lorsque peau ou paroi dominent le problème.','https://www.marc-divaris.com/liposuccion-du-ventre'],
  rfal: ['Liposuccion assistée par radiofréquence RFAL','Silhouette','Associe aspiration graisseuse et énergie thermique pour favoriser la contraction cutanée.','Une électrode interne et une externe délivrent une radiofréquence contrôlée. La méthode vise les surcharges avec laxité modérée et ne remplace pas toujours une résection de peau.','Les suites ressemblent à celles d’une liposuccion. Le raffermissement s’évalue progressivement au cours des mois.','https://www.marc-divaris.com/liposuccion-rfal'],
  'lipo-douce': ['Liposuccion douce','Silhouette','Aspiration limitée de petites zones graisseuses avec des canules fines.','Elle concerne une correction ciblée et peut parfois utiliser une anesthésie locale. Le terme “douce” ne supprime pas les risques d’un acte médical.','Œdème, ecchymoses et contention restent possibles ; la reprise dépend de la zone traitée.','https://www.marc-divaris.com/liposuccion-douce'],
  homme: ['Liposuccion masculine','Silhouette','Adapte le remodelage aux répartitions graisseuses masculines : abdomen, flancs, poitrine ou cou.','L’examen distingue graisse sous-cutanée, graisse viscérale, gynécomastie et peau relâchée. L’aspiration respecte les lignes musculaires.','Contention et reprise progressive sont nécessaires. La stabilité pondérale participe au maintien du résultat.','https://www.marc-divaris.com/liposuccion-masculine'],
  abdomino: ['Abdominoplastie','Silhouette','Retire un excès de peau abdominale et peut réparer une paroi distendue après grossesse ou amaigrissement.','La peau est retendue, les muscles peuvent être rapprochés et l’ombilic repositionné. Une liposuccion complémentaire peut harmoniser la taille.','C’est une chirurgie importante : gaine, prévention thromboembolique, soins de cicatrice et limitation des efforts sont nécessaires.','https://www.marc-divaris.com/abdominoplastie'],
  protheses: ['Prothèses mammaires','Silhouette','Augmentent ou restaurent le volume des seins en respectant le thorax et les tissus.','Volume, forme, voie d’abord et position devant ou derrière le muscle sont choisis individuellement. Une ptôse peut nécessiter un remodelage associé.','Douleur, tension et limitation des bras sont temporaires. Les implants demandent une surveillance et peuvent nécessiter une nouvelle intervention.','https://www.marc-divaris.com/protheses-mammaires'],
  reduction: ['Réduction mammaire','Silhouette','Diminue et remonte des seins trop volumineux pour améliorer confort et proportions.','Le chirurgien retire glande et peau, remodèle le sein et repositionne l’aréole. Les cicatrices dépendent du volume à corriger.','Un soutien-gorge médical est porté. Sensibilité et cicatrices évoluent pendant de nombreux mois.','https://www.marc-divaris.com/reduction-mammaire'],
  ptose: ['Ptôse mammaire','Silhouette','Remonte un sein tombant après grossesse, variation de poids ou vieillissement.','La glande est remodelée et l’aréole repositionnée, avec ou sans implant ou réduction. Les cicatrices varient selon la chute.','Le maintien postopératoire et les soins de cicatrice sont essentiels. Le résultat reste soumis au temps et aux variations de poids.','https://www.marc-divaris.com/ptose-mammaire'],
  fue: ['Greffe de cheveux FUE','Cheveux','Prélève les follicules un par un avant leur implantation dans les zones clairsemées.','La zone donneuse, l’alopécie et le capital folliculaire déterminent le plan. Ligne, angle et densité sont dessinés pour un résultat cohérent à long terme.','De petites croûtes précèdent souvent la chute temporaire des cheveux implantés, puis une repousse après plusieurs mois.','https://www.marc-divaris.com/greffe-cheveux-fue-paris'],
  fut: ['Greffe de cheveux FUT','Cheveux','Prélève une bandelette de cuir chevelu afin d’obtenir un grand nombre de greffons.','La zone donneuse est suturée, laissant une cicatrice linéaire cachée par les cheveux. Les follicules sont isolés puis implantés un à un.','La cicatrice donneuse demande des soins. Croûtes et chute initiale précèdent une repousse progressive.','https://www.marc-divaris.com/greffe-cheveux-paris'],
  auto: ['Greffe automatisée','Cheveux','Utilise un dispositif d’assistance pour certaines étapes du prélèvement folliculaire.','L’appareil aide à sélectionner et extraire les greffons, mais le diagnostic, la ligne frontale et l’implantation restent déterminants.','Rougeurs et petites croûtes sont proches des suites d’une FUE ; la repousse demande plusieurs mois.','https://www.marc-divaris.com/greffe-automatisee'],
  meso: ['Mésogreffe capillaire','Cheveux','Technique de stimulation utilisant un petit prélèvement tissulaire du patient préparé en microgreffons cellulaires.','Elle peut compléter une stratégie contre l’amincissement mais ne recrée pas des follicules sur une zone totalement dégarnie.','Rougeur et sensibilité locales sont possibles ; l’évolution s’évalue sur plusieurs mois.','https://www.marc-divaris.com/mesogreffe'],
  penoplastie: ['Pénoplastie médicale','Chirurgie intime','Augmente principalement la circonférence de la verge par injection d’acide hyaluronique résorbable.','Après anesthésie locale, le produit est placé sous la peau avec une canule puis réparti. Les attentes, dimensions normales et limites fonctionnelles sont discutées.','Œdème, ecchymoses, irrégularité ou infection sont possibles. Massage, abstinence et contrôles suivent un protocole précis.','https://www.marc-divaris.com/penoplastie'],
  gland: ['Augmentation du gland','Chirurgie intime','Modifie temporairement le volume du gland par acide hyaluronique.','Le produit est injecté avec mesure sous anesthésie locale. Le caractère résorbable et l’absence de garantie fonctionnelle doivent être compris.','Gonflement, hématome, irrégularité ou infection sont possibles ; abstinence et contrôle médical sont nécessaires.','https://www.marc-divaris.com/augmentation-du-gland'],
  nymphoplastie: ['Nymphoplastie','Chirurgie intime','Réduit ou remodèle les petites lèvres lorsqu’elles entraînent gêne, irritation ou demande persistante.','Le geste préserve autant que possible bords, sensibilité et symétrie. La diversité anatomique normale est expliquée avant toute décision.','Œdème et inconfort sont fréquents. Hygiène, vêtements amples, arrêt du sport et abstinence temporaire sont recommandés.','https://www.marc-divaris.com/nymphoplastie'],
  'levres-intimes': ['Augmentation des grandes lèvres','Chirurgie intime','Restaure un volume diminué par graisse autologue ou produit résorbable.','Le volume est réparti progressivement après examen d’une éventuelle asymétrie, perte de tissu ou autre pathologie.','Gonflement et ecchymoses sont possibles ; durée et stabilité dépendent du produit et de la résorption.','https://www.marc-divaris.com/augmentation-des-levres'],
  botox: ['Toxine botulique Botox','Injections','Diminue temporairement l’activité des muscles responsables de certaines rides d’expression.','L’analyse se fait au repos et en mouvement. De petites quantités sont injectées pour adoucir front, ride du lion ou pattes-d’oie sans figer le visage.','Rougeurs et ecchymoses sont possibles. Diffusion, asymétrie ou chute temporaire de paupière font partie des risques.','https://www.marc-divaris.com/botox'],
  'redessiner-levres': ['Redessiner les lèvres','Injections','Restaure contour, symétrie ou volume des lèvres avec de l’acide hyaluronique.','Les proportions du visage et le mouvement guident des injections mesurées. Le produit est résorbable et le gonflement masque le résultat initial.','Œdème et ecchymoses sont fréquents. Une complication vasculaire, rare mais urgente, doit être prise en charge immédiatement.','https://www.marc-divaris.com/redessiner-les-levres'],
  hydrafacial: ['La Diva Hydrafacial','Injections','Soin non chirurgical associant nettoyage, exfoliation, extraction et hydratation.','Le protocole est ajusté à la sensibilité et aux imperfections. Il améliore temporairement éclat et texture mais ne traite pas une pathologie cutanée.','Une rougeur transitoire est possible. Les bénéfices sont progressifs et nécessitent un entretien.','https://www.marc-divaris.com/diva-hydrafacial']
};

window.DIVARIS_LONGFORM = {
  temporal: [
    {title:'Le lifting temporal', paragraphs:[
      'Le lifting temporal permet de remonter l’extrémité externe des sourcils. Également appelé « pince mannequin », il ouvre le regard en repositionnant la queue du sourcil et en restaurant une distance plus harmonieuse entre les cils et le sourcil au niveau de la paupière supérieure.',
      'Cette intervention atténue l’excès de peau latéral. Elle ne doit pas être confondue avec le lifting frontal, dont les indications sont différentes et qui est aujourd’hui moins souvent pratiqué depuis le développement des injections de toxine botulique.'
    ]},
    {title:'La technique du lifting temporal', paragraphs:[
      'Le principe est de préserver entièrement les cheveux et d’éviter toute cicatrice placée devant leur ligne d’implantation. Une ouverture d’environ 2 cm est dissimulée dans la partie haute de la tempe.',
      'À partir de cette incision, le chirurgien travaille sous le muscle, dans un plan profond, jusqu’à la partie externe du sourcil. Un fil de suspension résorbable est ensuite positionné et fixé plus haut sur l’aponévrose temporale.',
      'Le sourcil adhère progressivement à sa nouvelle position pendant une quinzaine de jours. L’incision est refermée sans retirer de cheveux.',
      'Une variante endoscopique repose sur le même principe. Le décollement et le repositionnement sont alors réalisés avec une caméra et des instruments spécifiques introduits par de courtes incisions.'
    ]},
    {title:'Le lifting frontal', paragraphs:[
      'Le lifting frontal traite principalement des rides du front devenues importantes, notamment lorsque le patient ne souhaite pas recourir à la toxine botulique. Son indication est aujourd’hui plus limitée qu’auparavant.',
      'Lifting temporal et lifting frontal peuvent être réalisés séparément, conjointement ou à des moments différents, selon la peau, l’anatomie et la demande.'
    ]},
    {title:'Interventions associées', paragraphs:[
      'Selon l’examen, ces liftings peuvent être complétés par une liposuccion sous le menton, une chirurgie des paupières, un lipofilling destiné à restaurer certains volumes ou un traitement ciblé de muscles responsables de rides d’expression.',
      'L’objectif reste de corriger les effets du vieillissement sans appliquer une réponse identique à tous les visages. La zone vécue comme prioritaire varie fortement d’une personne à l’autre : sourcils, front, pattes-d’oie, poches sous les yeux, bajoues ou ovale.'
    ]},
    {title:'Une indication personnalisée', paragraphs:[
      'La perception du vieillissement comporte une part personnelle importante. Une modification anatomiquement discrète peut être très gênante pour une personne, tandis qu’un autre signe plus visible sera moins préoccupant.',
      'Le front, et en particulier la ride verticale située entre les sourcils, constitue une demande fréquente. La décision opératoire ne repose toutefois pas sur l’âge seul : qualité et souplesse de la peau, expression du visage, anatomie du sourcil et attentes doivent être analysées ensemble.'
    ]}
  ],
  fut: [
    {title:'Principe', paragraphs:[
      'La technique FUT, dite technique de la bandelette, consiste à prélever une bande de cuir chevelu dans la couronne. Ses dimensions dépendent de la surface à couvrir, de la densité capillaire de la zone donneuse et de la souplesse du cuir chevelu.',
      'La densité habituelle se situe entre 80 et 120 cheveux par cm². La bandelette mesure le plus souvent de 1 à 2 cm de hauteur sur 20 à 30 cm de longueur, ce qui peut représenter environ 2 000 à 6 000 cheveux.'
    ]},
    {title:'Prélèvement', paragraphs:[
      'L’incision est réalisée au bistouri. Elle laisse une cicatrice linéaire fine, normalement cachée par les cheveux voisins.',
      'Le principal inconvénient est cette cicatrice, dont l’évolution varie selon chaque patient. Un élargissement, une chute réactionnelle autour de la cicatrice ou une diminution temporaire de la sensibilité restent possibles, bien que peu fréquents.'
    ]},
    {title:'Avantages et indications', paragraphs:[
      'La zone donneuse peut être immédiatement dissimulée par les cheveux rabattus, ce qui facilite une reprise sociale rapide. Le temps opératoire est également plus court que pour certaines séances de FUE et se situe autour de trois heures selon l’importance du traitement.',
      'Selon le texte transmis, cette méthode est notamment réservée aux patients de plus de 50 ans qui ne souhaitent pas raser la zone donneuse et pour lesquels une cicatrice cachée à l’arrière du crâne n’est pas un obstacle.'
    ]},
    {title:'Tarif indicatif transmis', paragraphs:[
      'Entre 2 800 et 3 500 €. Ce tarif doit impérativement être vérifié et actualisé par le cabinet avant publication.'
    ]}
  ],
  fue: [
    {title:'Principe de la FUE', paragraphs:[
      'La FUE est une technique de prélèvement folliculaire sans bandelette ni scalpel. Les unités folliculaires sont extraites une à une avec un micropunch dont le diamètre est généralement inférieur à 1 mm.',
      'Plus le diamètre du punch est faible, plus les marques de prélèvement sont discrètes. La méthode permet également d’étendre la zone donneuse et d’augmenter le nombre d’unités folliculaires mobilisables.'
    ]},
    {title:'Répartition des greffons', paragraphs:[
      'Les unités folliculaires comportant un ou deux cheveux sont privilégiées pour reconstruire une ligne frontale naturelle. Les unités de trois ou quatre cheveux servent plutôt à densifier les zones situées en arrière et la tonsure.',
      'Le confort postopératoire est généralement supérieur à celui d’une bandelette et la cicatrisation de la zone donneuse est plus rapide.'
    ]},
    {title:'Techniques d’implantation', paragraphs:[
      'Deux grandes méthodes peuvent être utilisées. La première consiste à créer de petites fentes rapprochées, appelées slits, orientées selon l’axe naturel des cheveux. Les unités folliculaires sont ensuite placées dans ces ouvertures avec des micro-pinces.',
      'La seconde utilise un stylo implanteur de Choï. Son aiguille biseautée reçoit le follicule, puis un piston permet de le déposer dans le cuir chevelu. Cette méthode est notamment utile pour densifier une chevelure non rasée et faciliter une reprise sociale plus discrète.'
    ]},
    {title:'Déroulement du prélèvement', paragraphs:[
      'Après rasage de la zone donneuse, le patient est installé sur le ventre avec un coussin permettant de dégager le visage. L’intervention est réalisée sous anesthésie locale.',
      'Sous éclairage adapté et avec un grossissement optique, le punch est orienté selon l’axe du cheveu. Chaque unité folliculaire est libérée puis extraite avec une micro-pince. Les greffons sont conservés dans du sérum physiologique, contrôlés et triés avant leur implantation.'
    ]},
    {title:'Nombre de cheveux et résultat', paragraphs:[
      'Une séance peut implanter au minimum environ 1 200 unités folliculaires lorsque la surface est étendue. Une unité contient en moyenne 2,5 cheveux : 1 000 unités représentent donc approximativement 2 500 cheveux.',
      'Les bénéfices recherchés sont l’absence de cicatrice linéaire, un saignement limité, une ligne frontale naturelle et des douleurs postopératoires réduites. La repousse commence autour de la seizième semaine. Les cheveux greffés conservent les caractéristiques génétiques de la couronne et sont destinés à persister.'
    ]},
    {title:'Tarif indicatif transmis', paragraphs:[
      'Entre 3 000 et 5 500 € pour environ 1 200 à 2 000 unités folliculaires. Ce tarif doit impérativement être vérifié et actualisé par le cabinet avant publication.'
    ]}
  ],
  auto: [
    {title:'Technique SAFER', paragraphs:[
      'SAFER signifie Suction Assisted Follicle Extraction and Reimplantation. Cette méthode automatise une partie du prélèvement FUE et de la réimplantation afin de réduire le temps opératoire et de limiter les manipulations directes des greffons.',
      'La zone donneuse privilégiée se trouve dans la couronne. Elle est rasée à quelques millimètres afin de rendre visible l’orientation de sortie des cheveux.'
    ]},
    {title:'Prélèvement automatisé', paragraphs:[
      'Après anesthésie locale, le praticien choisit un punch de 0,8, 0,9 ou 1 mm. Le diamètre de 0,9 mm constitue une taille courante, tandis qu’un punch de 0,8 mm peut être utilisé lorsque les conditions le permettent.',
      'Le punch est relié à un contre-angle motorisé. Sa vitesse et son angle sont adaptés à chaque patient. Une pénétration progressive de 1 à 2 mm libère le follicule, qui est aspiré dans un récipient sans être saisi directement par une pince.',
      'Les unités folliculaires contiennent généralement un à trois cheveux. Elles sont triées, alignées sur une compresse, régulièrement hydratées et conservées au frais jusqu’à leur implantation.'
    ]},
    {title:'Implantation', paragraphs:[
      'La zone receveuse est anesthésiée localement. Des fentes très fines sont créées avec des microlames ou des aiguilles adaptées au diamètre des greffons.',
      'L’implanteur SAFER fonctionne comme un stylo : le greffon est aspiré dans son embout, placé à l’entrée de la fente puis déposé grâce à un piston commandé par pédale. Seuls les cheveux doivent rester visibles, le follicule étant installé dans le derme.'
    ]},
    {title:'Intérêt de l’automatisation', paragraphs:[
      'L’objectif principal est de préserver la qualité des unités folliculaires en réduisant leur manipulation par des pinces. La succion accompagne le prélèvement et l’implantation, tandis que le chirurgien conserve le contrôle de l’orientation, de la profondeur et de la répartition.'
    ]}
  ]
};
